version: '3.1'

services:
  postgres:
    container_name: postgres_test_app
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    restart: unless-stopped
